### ISSUE TITLE
"Check for Updates" causes FAST2 to close with no error.

### ISSUE THREAD

**Issue by eric963** [alec-hs/Flaxs-Arma-Server-Tool-2#58]
After selecting "Steam Mods" under the 'Main" section and then selecting the "Check for Updates" button causes FAST2 to close with no error.

Note: When selecting the "Update" button for and individual Mod there are no issues

These are two FAST2 errors appearing in my Windows Software Event log.
```
Faulting application name: FAST2.exe, version: 2.0.1.2, time stamp: 0x5bf6cc81
Faulting module name: KERNELBASE.dll, version: 10.0.17763.134, time stamp: 0xc30ded87
Exception code: 0xe0434352
Fault offset: 0x0011ab32
Faulting process id: 0x151c
Faulting application start time: 0x01d4a93e50f410ed
Faulting application path: G:\Games\FAST2\FAST2.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: d3a8caf6-a9e6-4d9c-96c8-5f2663753636
Faulting package full name: 
Faulting package-relative application ID: 
```
And...…
```
Application: FAST2.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.InvalidOperationException
   at System.Windows.Threading.Dispatcher.VerifyAccess()
   at System.Windows.DependencyObject.SetValue(System.Windows.DependencyProperty, System.Object)
   at FAST2.Models.SteamWebApi.ApiCall(System.String)
   at FAST2.Models.SteamWebApi.GetSingleFileDetails(Int32)
   at FAST2.Models.SteamMod.GetModInfo(System.Object)
   at FAST2.Models.SteamMod.UpdateInfoFromSteam()
   at FAST2.SteamMods+_Closure$__._Lambda$__10-0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at FAST2.SteamMods+VB$StateMachine_10_CheckForUpdates.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_0(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(System.Object)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Threading.Dispatcher.PushFrame(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Application.RunDispatcher(System.Object)
   at System.Windows.Application.RunInternal(System.Windows.Window)
   at System.Windows.Application.Run(System.Windows.Window)
   at FAST2.Application.Main()
```

**Comment by Drift91** [comment]
I'm having this issue as well. Originally I found that it meant a mod in the list had been removed from the workshop. Simple fix was to identify which mod was removed and remove it from FAST's list. Now it seems to crash constantly even though nothing's been taken off the workshop this time.

**Comment by Drift91** [comment]
So I found that, at least in my current case, the crash is caused by something in the `<ClientMods>` line.

Current config: https://pastebin.com/GQpzgUJA

As soon as I clicked "none" in the mods for that profile to deselect all the mods, it stoped crashing when I check for updates.

**Comment by alec-hs** [comment]
@Drift91 are you still seeing this error - finding it hard to replicate to fix.

**Comment by TomTucka** [comment]
We've been unable to replicate this, If people start seeing this issue again, please raise a new issue
